/*
	This file is an example of user-defined elements
	and callback functions. These are not part of the
	library. The purpose of this file is to keep Main
	clean and focused more on showcasing library
	functionality. This is the equivalent of a
	designer file auto-generated by WinForms, but
	created and maintained manually by the user.
*/

#include "elements.h"
#include "defs.h"

#define ARIAL_FONT 		"C:/Windows/Fonts/Arial.ttf" // test: custom fonts


char buffer1[50];
char buffer2[50];
char buffer3[20];

SDL_Color bg_color = { BG_DARK };

GUI_Button *button1;
GUI_Button *button2;
GUI_Button *button3;
GUI_Button *button4;
GUI_Slider *slider1;
GUI_Slider *slider2;
GUI_Label *label_title;
GUI_Label *label1;
GUI_Label *label2;
GUI_Label *label3;
GUI_Label *label4;
GUI_Label *label5;
GUI_Label *label6;
GUI_Label *label7;
GUI_Label *label8;
GUI_Label *label9;
GUI_Label *label_info;
GUI_Input *input1;
GUI_Checkbox *checkbox1;
GUI_Checkbox *checkbox2;
GUI_Checkbox *checkbox3;
GUI_RadioButton *radiobutton1;
GUI_RadioButton *radiobutton2;
GUI_RadioButton *radiobutton3;
GUI_RadioButton *radiobutton4;
GUI_RadioButton *radiobutton5;
GUI_RadioButton *radiobutton6;
GUI_RadioGroup *radiobuttons1;
GUI_RadioGroup *radiobuttons2;
GUI_ProgressBar *progressbar;
GUI_ListBox *listbox;


void InitElementList(void) {
	int offset_x = 118, offset_y = 80;

	SDL_Color blue =  { 122, 162, 192, 255 };

	label_title = GUI_CreateLabelEx(20, 25, "Welcome to the Demo!", ARIAL_FONT, 24);
	label_title->color = blue;

	// button with optional custom data to pass to button1_click()
	// any data can be passed to a void pointer, this example uses a string
	// in order to pass multiple arguments at once, a struct may be passed
	const char *message = "Hello, GUI!\n";
	button1 = GUI_CreateButton(offset_x, offset_y, "Click me!", button1_click);
	button1->args = (void*)message;
	button1->tag = "button";
	
	// example of a disabled button
	button2 = GUI_CreateButton(offset_x, button1->y + 32, "Disabled", NULL);
	button2->enabled = DISABLED;
	button2->tag = "button";

	// button to toggle between light and dark modes
	button3 = GUI_CreateButton(offset_x + button1->width + 10, button1->y, "Light mode", SwitchMode);
	button3->tag = "button";

	// example sliders: one of a short range and one of a long range
	// includes examples of snappy and smooth knob movement
	slider1 = GUI_CreateSlider(offset_x, button2->y + 50, 128, 0, 10, 1, 5);
	slider2 = GUI_CreateSliderEx(offset_x, slider1->y + 50, 128, 20, 10, 26, 1, 0, 50, 5, 0, SMOOTH); // or SNAP

	label1 = GUI_CreateLabel(offset_x, slider1->y + slider1->height + 6, buffer1);
	label2 = GUI_CreateLabel(offset_x, slider2->y + slider2->height + 6, buffer2);
	
	input1 = GUI_CreateInputField(offset_x, label2->y + 30, 185, 100, "Enter your text:");
	
	checkbox1 = GUI_CreateCheckbox(input1->x, input1->y + 38);
	checkbox2 = GUI_CreateCheckbox(input1->x, checkbox1->y + 26);
	checkbox3 = GUI_CreateCheckbox(input1->x, checkbox2->y + 26);
	checkbox3->enabled = 0;

	// radio buttons and groups to keep them linked
	radiobutton1 = GUI_CreateRadioButton(checkbox1->x + 40, checkbox1->y);
	radiobutton2 = GUI_CreateRadioButton(radiobutton1->x, radiobutton1->y + 26);
	radiobutton3 = GUI_CreateRadioButton(radiobutton2->x, radiobutton2->y + 26);
	radiobuttons1 = GUI_CreateRadioGroup();
	
	// labels attached to the radio buttons
	label4 = GUI_CreateLabel(radiobutton1->x + 24, radiobutton1->y, "One");
	label5 = GUI_CreateLabel(radiobutton2->x + 24, radiobutton2->y, "Two");
	label6 = GUI_CreateLabel(radiobutton3->x + 24, radiobutton3->y, "Three");

	radiobutton4 = GUI_CreateRadioButton(label4->x + 60, radiobutton1->y);
	radiobutton5 = GUI_CreateRadioButton(label5->x + 60, radiobutton4->y + 26);
	radiobutton6 = GUI_CreateRadioButton(label6->x + 60, radiobutton5->y + 26);
	radiobuttons2 = GUI_CreateRadioGroup();
	
	label7 = GUI_CreateLabel(radiobutton4->x + 24, radiobutton4->y, "Four");
	label8 = GUI_CreateLabel(radiobutton5->x + 24, radiobutton5->y, "Five");
	label9 = GUI_CreateLabel(radiobutton6->x + 24, radiobutton6->y, "Six");

	GUI_AddToRadioGroup(radiobuttons1, radiobutton1);
	GUI_AddToRadioGroup(radiobuttons1, radiobutton2);
	GUI_AddToRadioGroup(radiobuttons1, radiobutton3);
	GUI_AddToRadioGroup(radiobuttons2, radiobutton4);
	GUI_AddToRadioGroup(radiobuttons2, radiobutton5);
	GUI_AddToRadioGroup(radiobuttons2, radiobutton6);
	
	// progress bar and a button that simulates loading
	// pass progress bar pointer to button's arguments to access it
	progressbar = GUI_CreateProgressBar(input1->x, radiobutton6->y + 32, 185, 0, 100);

	label3 = GUI_CreateLabel(offset_x, progressbar->y + slider1->height + 6, buffer3);
	button4 = GUI_CreateButton(button3->x, button2->y, "Start!", InitiateLoading);
	button4->args = progressbar;
	button4->tag = "button";

	listbox = GUI_CreateListBox(button3->x + button3->width + 10, button3->y, "Set background color:", SetBackgroundColor);
	const char *entries[] = { "Theme Default", "Grey", "Red", "Green", "Teal", "Purple", "Pink", "Brown" };
	GUI_SetListEntries(listbox, entries, 8);

	// optional: set selected entry by index; this overrides the placeholder text
	GUI_SelectListEntry(listbox, 0);

	// extended label test with custom font and text size
	label_info = GUI_CreateLabelEx(listbox->x, input1->y,
			"Top-left button prints \"Hello, GUI!\"\n"
			"to the console.\n"
			" \n"
			"Bottom-right button (re)starts the\n"
			"loading bar.\n"
			" \n"
			"First slider snaps in place,\n"
			"second slider is smooth.\n"
			" \n"
			"Input field prints the input in the console\n"
			"on Enter.\n",
			ARIAL_FONT, 13);
}